stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data
    - src/prepare.py
    params:
    - prepare
    outs:
    - out/prepare
  train:
    cmd: python src/train.py
    deps:
    - out/prepare
    - src/train.py
    params:
    - train
    outs:
    - out/train
  test:
    cmd: python src/test.py
    deps:
    - out/train
    - src/test.py
    params:
    - test
    outs:
    - out/test
