prepare:
  image_features_path: data/Imaging_Features.xlsx
  clinical_features_path: data/Clinical_and_Other_Features.xlsx
  lunit_preds_path: data/lunit_predictions.xlsx
  patient_id_col: "Patient ID"
  target_col: "ER"
  out_path: out/prepare/df_image_features.parquet

train:
  out_path: out/train/model.json
  hparams_grid:
    max_depth: [2, 11]
    learning_rate: [0.01, 0.5]
    n_estimators: [2, 100]
  n_trials: 100
  cv: 5
  n_jobs: 1
  seed: 42

test:
  out_path: out/test/preds.csv
